sudo: true
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - curl --location https://raw.githubusercontent.com/twolfson/sublime-installer/master/install.sh | sh -s 3
  - subl --version
  - npm install -g gulp
  - npm install
script:
  - gulp
